kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: ubuntu:focal-20210609
  commands:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -yq build-essential git wget curl
  - make build-appimage
