kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: ubuntu:focal-20210609
  environment:
    SCP_ID:
      from_secret: id
    SCP_PUB:
      from_secret: pub
  commands:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -yq build-essential file git wget curl
  - git fetch --tags
  - mkdir ~/.ssh
  - echo "$${SCP_ID}" | cat > ~/.ssh/id_rsa
  - echo "$${SCP_PUB}" | cat > ~/.ssh/id_rsa.pub
  - make build-appimage
  - CURRENT_BRANCH=${DRONE_SOURCE_BRANCH}
  - BRANCH=""; if [ "$${CURRENT_BRANCH}" != "master" ]; then BRANCH="$${CURRENT_BRANCH}_"; fi
  - VERSION=$(git describe --tags)
  - echo "Uploading version $${BRANCH}bcad-x86_64-$${VERSION} from $${CURRENT_BRANCH}"
  - |
    GIT_TAG=$(git describe --tags --no-abbrev)
    curl --insecure -u droneio: --key ~/.ssh/id_rsa --pubkey ~/.ssh/id_rsa.pub -T bcad-x86_64.AppImage sftp://10.218.35.100/srv/deb-repositories/archive/drone/bcad/$${BRANCH}bcad-x86_64-$${VERSION}.AppImage
