kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: ubuntu:bionic-20210615.1
  commands:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -yq build-essential git wget curl cmake libfreetype6-dev libtbb-dev libfreeimage-dev libvtk6-dev flex bison rapidjson-dev tcl-dev tk-dev doxygen graphviz
  - make build-appimage
