#!/bin/bash
LD_LIBRARY_PATH=$(pwd)/ext/usr/lib:${LD_LIBRARY_PATH} PYTHONPATH=$(pwd)/ext/usr/lib/python3/site-packages:$(pwd)/ext/usr/lib/python3.7/site-packages:${PYTHONPATH} python3 -m bcad.binterpreter.scl "$@"
